# Generated by Django 3.0.8 on 2020-07-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='author',
            field=models.CharField(default='', max_length=30),
        ),
    ]
