# Generated by Django 3.0.8 on 2020-07-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200716_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.CharField(default='', max_length=30),
        ),
    ]
