# Generated by Django 3.0.8 on 2020-07-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200716_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
