# Generated by Django 3.0.8 on 2020-07-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid'),
        ),
    ]
