# Generated by Django 3.0.8 on 2020-07-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200716_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='current_bid',
            new_name='bid',
        ),
    ]
