# Generated by Django 3.0.8 on 2020-07-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20200719_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.CharField(default='0.0', max_length=90),
        ),
    ]
