# Generated by Django 3.0.8 on 2020-07-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20200719_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.Bid'),
        ),
    ]
