# Generated by Django 3.0.8 on 2020-07-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='in_watchlist',
        ),
    ]
